In [2]:
from sklearn import linear_model

In [3]:
import Modules.ml_data as datahlpr


In [4]:
X, Y = datahlpr.load_food_truck_data()

In [5]:
reg = linear_model.LinearRegression()

In [6]:
reg.fit(X,Y)

/Users/jaikumar/.pyenv/versions/3.6.2/lib/python3.6/site-packages/scipy/linalg/basic.py:1018: RuntimeWarning: internal gelsd driver lwork query error, required iwork dimension not returned. This is likely the result of LAPACK bug 0038, fixed in LAPACK 3.2.2 (released July 21, 2010). Falling back to 'gelss' driver.
  warnings.warn(mesg, RuntimeWarning)


LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [7]:
reg.coef_

array([[ 1.19303364]])

In [8]:
from Modules.regression import *

In [9]:
init_X = initialize_feature(X, 0)

In [10]:
reg.fit(init_X,Y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
reg.coef_

array([[ 0.        ,  1.19303364]])

In [5]:
import numpy as np


df = np.array([[-1, 3], [0, 5]])
gh = np.where(df >= 0, 1, 0)
print(gh)

[[0 1]
 [1 1]]
